name: build

on:
    - push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Cloning repos
            uses: actions/checkout@v3

            - name: Setup Nodejs
            uses: actions/setup-nodejs@v3

            - name: Install dependencies
            run: make install

            - name: Make lint
            run: make install